import { PARK_NAME, PARK_ADDRESS, LOGO_SRC } from './branding'

// ── Professional exports (Excel + letterhead CSV) ─────────────────────────
// Same letterhead as the printable Reports page: park logo, name, address,
// report title, the filters that were applied, who generated it and when,
// then a styled table. A real CSV can't carry a logo, colours or column
// widths, so the Excel (.xlsx) export is the fully formatted version and the
// CSV carries the same letterhead as text rows above the data table.

export interface ReportColumn<T> {
  header: string
  value: (row: T) => string | number | null | undefined
  /** Excel column width in characters (default 18). */
  width?: number
  align?: 'left' | 'center' | 'right'
  /** Excel number format, e.g. '"₱"#,##0.00' (return a number from value). */
  numFmt?: string
}

export interface ReportMeta {
  /** e.g. "Bookings Report" */
  title: string
  /** Human-readable filter summary, e.g. "Status: Pending · Payment: Paid" */
  filters: string
  preparedBy: string
}

const stamp = () => new Date().toLocaleString('en-PH', { dateStyle: 'long', timeStyle: 'short' })

function download(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  a.remove()
  URL.revokeObjectURL(url)
}

function csvEscape(value: string | number | null | undefined): string {
  const s = value === null || value === undefined ? '' : String(value)
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s
}

// ── CSV with letterhead rows ──────────────────────────────────────────────
export function exportReportCsv<T>(
  filename: string, rows: T[], columns: ReportColumn<T>[], meta: ReportMeta,
) {
  const line = (cells: (string | number | null | undefined)[]) => cells.map(csvEscape).join(',')
  const lines = [
    line([PARK_NAME]),
    line([PARK_ADDRESS]),
    line([meta.title.toUpperCase()]),
    line([`Filters: ${meta.filters}`]),
    line([`Generated: ${stamp()}  ·  By: ${meta.preparedBy}`]),
    line([`Total records: ${rows.length}`]),
    '',
    line(columns.map(c => c.header)),
    ...rows.map(r => line(columns.map(c => c.value(r)))),
    '',
    '',
    line(['Prepared by:', meta.preparedBy, '', 'Verified by:', '______________________']),
    '',
    line([`${PARK_NAME} — Internal Report, Confidential  ·  Auto-generated by AmuseFlow System`]),
  ]
  // BOM so Excel reads UTF-8 (₱, accents) correctly.
  const blob = new Blob(['﻿' + lines.join('\r\n')], { type: 'text/csv;charset=utf-8;' })
  download(blob, filename.endsWith('.csv') ? filename : `${filename}.csv`)
}

// ── Formatted Excel workbook ──────────────────────────────────────────────
export async function exportReportExcel<T>(
  filename: string, rows: T[], columns: ReportColumn<T>[], meta: ReportMeta,
) {
  // Loaded on demand so ExcelJS (large) stays out of the main bundle.
  const ExcelJS = (await import('exceljs')).default
  const wb = new ExcelJS.Workbook()
  wb.creator = 'AmuseFlow System'
  wb.created = new Date()
  const ws = wb.addWorksheet(meta.title.slice(0, 31), {
    views: [{ showGridLines: false }],
    pageSetup: { orientation: 'landscape', fitToPage: true, fitToWidth: 1, fitToHeight: 0 },
  })

  const colCount = Math.max(columns.length, 4)
  columns.forEach((c, i) => { ws.getColumn(i + 1).width = c.width ?? 18 })
  const lastCol = colCount
  // Letterhead text starts in column B (right next to the logo in column A).
  const mergeRow = (r: number) => ws.mergeCells(r, 2, r, lastCol)

  // Letterhead — logo at left (cols A–B), text at right of it.
  ws.getRow(1).height = 30
  ws.getRow(2).height = 18
  ws.getRow(3).height = 6
  try {
    const res = await fetch(LOGO_SRC)
    if (res.ok) {
      const imgId = wb.addImage({ buffer: await res.arrayBuffer(), extension: 'png' })
      ws.addImage(imgId, { tl: { col: 0.08, row: 0.05 }, ext: { width: 50, height: 50 } })
    }
  } catch { /* logo is decorative — export still succeeds without it */ }

  ws.getCell(1, 2).value = PARK_NAME
  ws.getCell(1, 2).font = { name: 'Arial', size: 20, bold: true, color: { argb: 'FF111827' } }
  ws.getCell(1, 2).alignment = { vertical: 'middle', indent: 0 }
  mergeRow(1)
  ws.getCell(2, 2).value = PARK_ADDRESS
  ws.getCell(2, 2).font = { name: 'Arial', size: 10, color: { argb: 'FF6B7280' } }
  ws.getCell(2, 2).alignment = { vertical: 'top', indent: 0 }
  mergeRow(2)

  // Rule under the letterhead
  for (let c = 1; c <= lastCol; c++) {
    ws.getCell(3, c).border = { top: { style: 'medium', color: { argb: 'FF1F2937' } } }
  }

  // Title + meta block
  ws.getCell(5, 1).value = meta.title.toUpperCase()
  ws.getCell(5, 1).font = { name: 'Arial', size: 14, bold: true }
  ws.mergeCells(5, 1, 5, lastCol)
  const metaLines = [
    `Filters: ${meta.filters}`,
    `Generated: ${stamp()}   ·   Prepared by: ${meta.preparedBy}`,
    `Total records: ${rows.length}`,
  ]
  metaLines.forEach((t, i) => {
    const r = 6 + i
    ws.getCell(r, 1).value = t
    ws.getCell(r, 1).font = { name: 'Arial', size: 9, color: { argb: 'FF6B7280' } }
    ws.mergeCells(r, 1, r, lastCol)
  })

  // Table header
  const headerRowNo = 10
  const header = ws.getRow(headerRowNo)
  header.height = 22
  columns.forEach((c, i) => {
    const cell = header.getCell(i + 1)
    cell.value = c.header
    cell.font = { name: 'Arial', size: 10, bold: true, color: { argb: 'FFFFFFFF' } }
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF1F2937' } }
    cell.alignment = { vertical: 'middle', horizontal: c.align ?? 'left', wrapText: true }
    cell.border = { bottom: { style: 'thin', color: { argb: 'FF111827' } } }
  })

  // Body — zebra striping, thin light borders
  const thin = { style: 'thin' as const, color: { argb: 'FFE5E7EB' } }
  rows.forEach((row, ri) => {
    const r = ws.getRow(headerRowNo + 1 + ri)
    columns.forEach((c, ci) => {
      const cell = r.getCell(ci + 1)
      const v = c.value(row)
      cell.value = v === undefined ? null : v
      cell.font = { name: 'Arial', size: 10 }
      if (c.numFmt) cell.numFmt = c.numFmt
      cell.alignment = { vertical: 'middle', horizontal: c.align ?? 'left', wrapText: true }
      cell.border = { top: thin, bottom: thin, left: thin, right: thin }
      if (ri % 2 === 1) cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF9FAFB' } }
    })
  })

  // Signature block — same "Prepared by / Verified by" as the printed report.
  // Blank line on purpose for a pen signature; Prepared by shows the name below.
  const sigRow = headerRowNo + rows.length + 4
  const n = Math.max(columns.length, 6) // guard: very narrow tables still get two non-overlapping blocks
  const leftEnd = Math.max(2, Math.floor(n * 0.4))
  const rightStart = Math.max(leftEnd + 2, n - leftEnd + 1)
  const sigBlocks: [number, number, string, string][] = [
    [1, leftEnd, meta.preparedBy, 'Prepared by'],
    [rightStart, n, '', 'Verified by'],
  ]
  ws.getRow(sigRow).height = 38
  sigBlocks.forEach(([from, to, name, label]) => {
    ws.mergeCells(sigRow, from, sigRow, to)
    for (let c = from; c <= to; c++) {
      ws.getCell(sigRow, c).border = { bottom: { style: 'thin', color: { argb: 'FF1F2937' } } }
    }
    ws.mergeCells(sigRow + 1, from, sigRow + 1, to)
    ws.getCell(sigRow + 1, from).value = name || ' '
    ws.getCell(sigRow + 1, from).font = { name: 'Arial', size: 10, bold: true }
    ws.mergeCells(sigRow + 2, from, sigRow + 2, to)
    ws.getCell(sigRow + 2, from).value = label
    ws.getCell(sigRow + 2, from).font = { name: 'Arial', size: 9, color: { argb: 'FF6B7280' } }
  })

  // Footer
  const footerNo = sigRow + 5
  ws.getCell(footerNo, 1).value = `${PARK_NAME} — Internal Report, Confidential  ·  Auto-generated by AmuseFlow System`
  ws.getCell(footerNo, 1).font = { name: 'Arial', size: 8, italic: true, color: { argb: 'FF9CA3AF' } }
  ws.mergeCells(footerNo, 1, footerNo, lastCol)

  // Usability: freeze through the header, filter dropdowns, repeat header when printed
  ws.views = [{ state: 'frozen', ySplit: headerRowNo, showGridLines: false }]
  ws.autoFilter = { from: { row: headerRowNo, column: 1 }, to: { row: headerRowNo, column: columns.length } }
  ws.pageSetup.printTitlesRow = `${headerRowNo}:${headerRowNo}`

  const buf = await wb.xlsx.writeBuffer()
  download(
    new Blob([buf], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' }),
    filename.endsWith('.xlsx') ? filename : `${filename}.xlsx`,
  )
}
